spring.application.name=ai-study-system
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/ai_study_db
spring.datasource.username=root
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway (disable for now until entities are stable)
spring.flyway.enabled=false

youtube.api.key=${youtube_api_key}
spring.devtools.add-properties=false

ai.service.url=http://localhost:5000
spring.codec.max-in-memory-size=10MB
groq.api.key=${groq_api}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher